---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: huginn-pvc
  namespace: huginn
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn-db
  namespace: huginn
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: huginn-db
    app.kubernetes.io/version: "12.6"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: huginn
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: huginn-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: huginn-db
        app.kubernetes.io/version: "12.6"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: huginn
    spec:
      containers:
      - name: postgres
        image: postgres:12.6-alpine
        env:
          - name: POSTGRES_DB
            value: huginn
          - name: PGDATA
            value: /var/lib/postgresql/data/db
        envFrom:
          - secretRef:
              name: huginn-db-secret
        volumeMounts:
          - name: db-storage
            mountPath: /var/lib/postgresql/data

      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: huginn-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: huginn-db
  namespace: huginn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: huginn-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
